### ISSUE TITLE
Error in building docker image

### ISSUE THREAD

**Issue by shmakn99** [isl-org/MiDaS#128]
```
Sending build context to Docker daemon  1.433MB
Step 1/9 : FROM nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04
 ---> 3be0d968ef0f
Step 2/9 : RUN apt-get update && apt-get -y install     python3     python3-pip     libsm6     libxext6     libxrender-dev     curl     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 826c65a8a5fc
Step 3/9 : RUN pip3 install torch~=1.8 torchvision opencv-python~=3.4 timm
 ---> Running in 962a0a6f29cb
Collecting torch~=1.8
  Downloading https://files.pythonhosted.org/packages/9a/f1/735e39ed0e3877ff02ffe625989bb421747c3dfd256e37ed92ad32c986be/torch-1.9.1-cp36-cp36m-manylinux1_x86_64.whl (831.4MB)
Collecting torchvision
  Downloading https://files.pythonhosted.org/packages/8e/3b/73e2cf095f0a9d0f26b008cbfc009512c53bb2a445723aaad54b33e58cb5/torchvision-0.10.1-cp36-cp36m-manylinux1_x86_64.whl (22.1MB)
Collecting opencv-python~=3.4
  Downloading https://files.pythonhosted.org/packages/d7/71/d5ac1ee0e9906a2edec2224da53e43f91291217a664c523219361db23395/opencv-python-3.4.15.55.tar.gz (87.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4q4debsr/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```
This build command fails because of the skbuild module is not there. Is it supposed to happen?

**Comment by ranftlr** [comment]
Thanks for reporting, will have a look in the coming days and will update the docker image.
