### ISSUE TITLE
Unflatten & ONNX export

### ISSUE THREAD

**Issue by carsonswope** [isl-org/MiDaS#182]
I am able to export the MiDaS model w/ DPT large backbone to ONNX using `torch.onnx.export` _almost_ without modifying the model at all.

The one issue I have found is from this line in `vit.py`:

```
unflatten = nn.Sequential(
    nn.Unflatten(
        2,
        torch.Size(
            [
                h // pretrained.model.patch_size[1],
                w // pretrained.model.patch_size[0],
            ]
        ),
    )
)
```

Which gives me this error when attempting to export to ONNX, from `flatten.py` in pytorch (I'm running torch 1.11.0):

`TypeError: unflattened_size must be tuple of ints, but found element of type Tensor at pos 0`

We don't want to cast `h` and `w` to `int`, because then the dimensionality will be hard-coded into the model and I would like the onnx model to support dynamic height & width.

So, why not do something like this instead:

`unflatten = lambda layer: layer.view((b, layer.shape[1], h // pretrained.model.patch_size[1], w // pretrained.model.patch_size[0]))`

This seems to me to be functionally equivalent, if not as elegant because you also have to pass `b` and the channel count for each layer into the function as well.

**Comment by aswanthkrishna** [comment]
where you able to export the new models to onnx?

**Comment by carsonswope** [comment]
@aswanthkrishna yes, with the above modification, I was able to export to onnx

**Comment by scarletshroud** [comment]
@carsonswope Did you work with models, dpt_swin2_tiny_256, dpt_levit_224? And did you use make_onnx_model.py script or other custom one? I'm trying to convert model data to onnx format with make_onnx_model.py, but I get the following error:
```
raise errors.SymbolicValueError("step!=1 is currently not supported", self)
torch.onnx.errors.SymbolicValueError: step!=1 is currently not supported  [Caused by the value '789 defined in (%789 : Float(1, 14, 14, 384, strides=[196, 14, 1, 196], requires_grad=1, device=cpu) = onnx::Reshape(%757, %788), scope: midas.dpt_depth.DPTDepthModel::/torch.nn.modules.container.Sequential::blocks/timm.models.levit.AttentionSubsample::blocks.8/torch.nn.modules.container.Sequential::q/timm.models.levit.Subsample::q.0 # C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py:234:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Reshape'.]
```
I would be very grateful if you could push me a solution, I am new to this area.

Trace
```
Traceback (most recent call last):
  File "J:\algorithms\MiDaS-master\tf\make_onnx_model.py", line 131, in <module>
    run(MODEL_PATH)
  File "J:\algorithms\MiDaS-master\tf\make_onnx_model.py", line 120, in run
    torch.onnx.export(model, sample, ntpath.basename(model_path).rsplit('.', 1)[0]+'.onnx', opset_version=9)
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\symbolic_opset9.py", line 3880, in slice
    raise errors.SymbolicValueError("step!=1 is currently not supported", self)
torch.onnx.errors.SymbolicValueError: step!=1 is currently not supported  [Caused by the value '789 defined in (%789 : Float(1, 14, 14, 384, strides=[196, 14, 1, 196], requires_grad=1, device=cpu) = onnx::Reshape(%757, %788), scope: midas.dpt_depth.DPTDepthModel::/torch.nn.modules.container.Sequential::blocks/timm.models.levit.AttentionSubsample::blocks.8/torch.nn.modules.container.Sequential::q/timm.models.levit.Subsample::q.0 # C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py:234:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Reshape'.]
    (node defined in C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py(234): forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\container.py(217): forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py(383): forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\container.py(217): forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py(524): forward_features
J:\algorithms\MiDaS-master\tf/..\midas\backbones\levit.py(10): forward_levit
J:\algorithms\MiDaS-master\tf/..\midas\dpt_depth.py(114): forward
J:\algorithms\MiDaS-master\tf/..\midas\dpt_depth.py(166): forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_trace.py(118): wrapper
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_trace.py(127): forward
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_trace.py(1268): _get_trace_graph
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py(893): _trace_and_get_graph_from_model
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py(989): _create_jit_graph
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py(1113): _model_to_graph
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py(1548): _export
C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py(506): export
J:\algorithms\MiDaS-master\tf\make_onnx_model.py(120): run
J:\algorithms\MiDaS-master\tf\make_onnx_model.py(131): <module>
)

    Inputs:
        #0: 757 defined in (%757 : Float(1, 196, 384, strides=[75264, 1, 196], requires_grad=1, device=cpu) = onnx::Add(%740, %756), scope: midas.dpt_depth.DPTDepthModel::/torch.nn.modules.container.Sequential::blocks/timm.models.levit.Residual::blocks.7 # C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py:223:0
    )  (type 'Tensor')
        #1: 788 defined in (%788 : int[] = prim::ListConstruct(%762, %787, %787, %786), scope: midas.dpt_depth.DPTDepthModel::/torch.nn.modules.container.Sequential::blocks/timm.models.levit.AttentionSubsample::blocks.8/torch.nn.modules.container.Sequential::q/timm.models.levit.Subsample::q.0
    )  (type 'List[int]')
    Outputs:
        #0: 789 defined in (%789 : Float(1, 14, 14, 384, strides=[196, 14, 1, 196], requires_grad=1, device=cpu) = onnx::Reshape(%757, %788), scope: midas.dpt_depth.DPTDepthModel::/torch.nn.modules.container.Sequential::blocks/timm.models.levit.AttentionSubsample::blocks.8/torch.nn.modules.container.Sequential::q/timm.models.levit.Subsample::q.0 # C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\timm\models\levit.py:234:0
    )  (type 'Tensor')
```
