### ISSUE TITLE
no timm despite pip install

### ISSUE THREAD

**Issue by j2l** [isl-org/MiDaS#186]
Hello, 
In my dedicated python environment, I tried with latest timm and forced 0.4.5 without luck:
```
pip install timm==0.4.5
Defaulting to user installation because normal site-packages is not writeable
Collecting timm==0.4.5
  Downloading timm-0.4.5-py3-none-any.whl (287 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.4/287.4 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.4 in /home/pm/.local/lib/python3.10/site-packages (from timm==0.4.5) (1.12.1)
Requirement already satisfied: torchvision in /home/pm/.local/lib/python3.10/site-packages (from timm==0.4.5) (0.13.1)
Requirement already satisfied: typing-extensions in /home/pm/.local/lib/python3.10/site-packages (from torch>=1.4->timm==0.4.5) (4.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/lib/python3/dist-packages (from torchvision->timm==0.4.5) (9.0.1)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from torchvision->timm==0.4.5) (1.21.5)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from torchvision->timm==0.4.5) (2.25.1)
Installing collected packages: timm
Successfully installed timm-0.4.5
(midas) pm@pop-os:~/Documents/github$ python run.py --model_type dpt_large
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "/home/pm/Documents/github/midas/dpt_depth.py", line 6, in <module>
    from .blocks import (
  File "/home/pm/Documents/github/midas/blocks.py", line 4, in <module>
    from .vit import (
  File "/home/pm/Documents/github/midas/vit.py", line 3, in <module>
    import timm
ModuleNotFoundError: No module named 'timm'
```
Any idea?

**Comment by NielsRogge** [comment]
For easy inference see #259

**Comment by j2l** [comment]
Thanhks @NielsRogge  I forgot about this ticket (sept 22).
